language: c

before_install:
 - sudo add-apt-repository ppa:irie/blender -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake blender python3.4-dev libgl1-mesa-dev libsdl1.2debian xvfb

script: "time ./.travis.bash"

notifications:
  irc: "irc.freenode.org#morse"
