language: python
python: "3.2"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake python3.2-dev libgl1-mesa-dev libsdl1.2debian xvfb

script: "time ./.travis.bash"

notifications:
  irc: "irc.freenode.org#morse"
