# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gyro_poster', [dirname(__file__)])
        except ImportError:
            import _gyro_poster
            return _gyro_poster
        if fp is not None:
            try:
                _mod = imp.load_module('_gyro_poster', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gyro_poster = swig_import_helper()
    del swig_import_helper
else:
    import _gyro_poster
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def init_data(*args):
  return _gyro_poster.init_data(*args)
init_data = _gyro_poster.init_data

def post_data(*args):
  return _gyro_poster.post_data(*args)
post_data = _gyro_poster.post_data

def finalize(*args):
  return _gyro_poster.finalize(*args)
finalize = _gyro_poster.finalize
class pomPoster(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pomPoster, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pomPoster, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _gyro_poster.new_pomPoster(*args)
        try: self.this.append(this)
        except: self.this = this
    def put(self, *args): return _gyro_poster.pomPoster_put(self, *args)
    __swig_destroy__ = _gyro_poster.delete_pomPoster
    __del__ = lambda self : None;
pomPoster_swigregister = _gyro_poster.pomPoster_swigregister
pomPoster_swigregister(pomPoster)



